### ISSUE TITLE
UI SDK Json parsing exception

### ISSUE THREAD

**Issue by rprasadb2000** [veritrans/veritrans-android#101]
While using UI SDk in sandbox mode, following exception is displayed and transaction is hung
I/VeritransSDK: General error occurred com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

**Comment by rprasadb2000** [comment]
Using Android 0.11.2

**Comment by rakawestu** [comment]
@rprasadb2000 Have you implement the merchant server from [Mobile-Merchant-Server](github.com/veritrans/mobile-merchant-server). It's required to run charging transaction the mobile SDK.

**Comment by rprasadb2000** [comment]
Hi,


The link for Mobile-Merchant-Server is not opening. You are right this 
part is not done yet. Please provide the link URL so that I can 
implement the same.

Thanks
Rajendra Prasad

**Comment by dindatisi** [comment]
Hi @rprasadb2000 please use this link [](https://github.com/veritrans/mobile-merchant-server)

**Comment by rprasadb2000** [comment]
Thanks.

By any chance do you have PHP reference implementation also.

**Comment by dindatisi** [comment]
Hi, unfortunately we only provide reference in node.js. But for the PHP implementation, it should be pretty similar with VT Direct charge implementation here http://docs.veritrans.co.id/en/vtdirect/integration_cc.html
