### ISSUE TITLE
Some feedback & bug report from meeting with BursaTukang

### ISSUE THREAD

**Issue by rizdaprasetya** [veritrans/veritrans-android#11]
On previous SDK & (possibly) this new SDK, expect merchant to implement save token flow on their server side, but most case merchant dont need save token flow (OneClick & TwoClick). So the error happen when SDK try to get saved token from server. The default CC payment UI seems like trying to get saved token from server before displaying the payment UI.

In default CC payment UI, there's option to save credit card, even when merchant don't use one click & two click. this option should be hidden.

Validation on field phone number need to be reviewed on the logic, because merchant said it only accept number with +62, and can't accept 10 digit length phone number.

Amount format for some payment method is inconsistent, for example 10000 IDR would be displayed as 10.000 and sometimes 10000 without separator. (This happen on previous SDK, haven't checked this new SDK).

Need to make sure merchant understand what is need to be implemented in server side. Maybe some sample.

*It's been already passed to Dinda & Mobile team via skype on May 26th. But I post it again here as requested by @sreeix  to make sure it's archieved.
Thanks.

**Comment by dindatisi** [comment]
thanks @rizdaprasetya !  we already fix some of your feedbacks in the newest version, namely:
- hide option to save CC when merchant don't use oneclick & two click
- fix phone number validation (now we allow 9-15digits phone number)
- ensure amount format is consistent (now all amount is written without separator)

**Comment by rakawestu** [comment]
Yes. This issue was fixed on `0.10.1` release. #5 #6
