### ISSUE TITLE
Invalid URL for : Veritrans Merchant server Reference Implementation

### ISSUE THREAD

**Issue by rizdaprasetya** [veritrans/veritrans-android#15]
Hi team,

step **no.5** of this **prerequisite** section:
https://github.com/veritrans/veritrans-android/blob/master/README.md#prerequsites
The link to  **Veritrans Merchant server Reference Implementation** is not found.
This potentially will leave merchant unable to find sample server implementation.

Thanks.

**Comment by sreeix** [comment]
That is my bad. I pointed it to a non existing URL. Will update asap.

**Comment by rakawestu** [comment]
Example server implementation has been updated in readme.
