### ISSUE TITLE
404 Error message improvement

### ISSUE THREAD

**Issue by rizdaprasetya** [veritrans/veritrans-android#16]
Several merchant mistakenly insert value of veritrans' API url instead of their server URL
in the _build.gradle_ :
```
buildConfigField "String", "BASE_URL", <MERCHANT_BASE_URL_SANDBOX>
```
This will result in error message:
**Unknown Error: 404 not found**

Maybe we can alter this error message to something more descriptive like:
**Invalid URL: 404 not found. Please make sure you set BASE_URL to merchant (your) server in _build.gradle_** 

Anyway, this mistakes happen even though the documentation is clearly say :
>     Add the Merchant server URL and the Veritrans client Key in the configuration into your build.gradle file (Note: We have different CLIENT_KEY values for sandbox and production)

Maybe we should add more explanation:
>     Add the Merchant server URL **(your server URL)** and the Veritrans client Key in the configuration into your build.gradle file (Note: We have different CLIENT_KEY values for sandbox and production)

Current 404 error message:
![1465106470327screenshot_2016-06-04-19-23-46](https://cloud.githubusercontent.com/assets/13027142/15803958/d6814dd0-2b21-11e6-8180-a0802cd1cbe0.png)

**Comment by rakawestu** [comment]
Ok. Will take a look and fix this issue after I done fixing some internal issues today.
