### ISSUE TITLE
Failed to resolve: com.midtrans:widget

### ISSUE THREAD

**Issue by mja46** [veritrans/veritrans-android#166]
gradle failed build because 
developmentCompile 'com.midtrans:widget:1.0.1-SANDBOX'
    productionCompile 'com.midtrans:widget:1.0.1'

Failed to resolve: com.midtrans:widget:1.0.1-SANDBOX

How to solve this?
thanks before

**Comment by rakawestu** [comment]
Have you add this line to your root's `build.gradle` ?

```Groovy
repositories {
    jcenter()
        // Add the midtrans repository into the list of repositories
        maven { url "http://dl.bintray.com/pt-midtrans/maven" }
    }
```

Also we just updates SDK into new version (`1.1.1`). Please check wiki again [here](https://github.com/veritrans/veritrans-android/wiki/Midtrans-Payment-Widget).

Also there's typo on our docs that just fixed few minutes ago. It's not `widget` but `widgets`.

**Comment by mja46** [comment]
yes i use sample source code from this github. this full gradle

apply plugin: 'com.android.application'
buildscript {
    repositories {
        jcenter()
    }
}
repositories {
    jcenter()
    maven { url "http://dl.bintray.com/pt-midtrans/maven" }
}
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.midtrans.sdk.example"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }

    productFlavors {
        development {
            applicationId "com.midtrans.sdk.sample.development"
            buildConfigField "String", "BASE_URL", "MERCHANT_BASE_URL_SANDBOX"
            buildConfigField "String", "CLIENT_KEY", ""
        }
        production {
            applicationId "com.midtrans.sdk.sample.production"
            buildConfigField "String", "BASE_URL", "MERCHANT_BASE_URL_PRODUCTION"
            buildConfigField "String", "CLIENT_KEY", ""
        }
    }
    buildTypes {
        debug {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    // Android support
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:design:23.4.0'
    compile 'com.android.support:cardview-v7:23.4.0'



    androidTestCompile('com.android.support.test:runner:0.3') {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    androidTestCompile('com.android.support.test:rules:0.3') {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2') {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    androidTestCompile('com.android.support.test.espresso:espresso-intents:2.2') {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    androidTestCompile('com.android.support.test.espresso:espresso-contrib:2.2') {
        exclude group: 'com.android.support', module: 'support-annotations'
        exclude group: 'com.android.support', module: 'appcompat'
        exclude group: 'com.android.support', module: 'support-v4'
        exclude module: 'recyclerview-v7'
    }
    // For using the Veritrans Sandbox
    compile 'com.midtrans:corekit:1.0.1-SANDBOX'
    // For using the Veritrans Production
    compile 'com.midtrans:corekit:1.0.1'
    // For using the Veritrans Sandbox
    compile 'com.midtrans:uikit:1.0.1-SANDBOX'
    // For using the Veritrans Production
    compile 'com.midtrans:uikit:1.0.1'
    compile ('com.midtrans:scancard:1.0.1'){
        exclude module: 'uikit'
    }
    developmentCompile 'com.midtrans:widget:1.0.1-SANDBOX'
    productionCompile 'com.midtrans:widget:1.0.1'

     // Leak Canary
    developmentCompile 'com.squareup.haha:haha:2.0.3'
    developmentCompile 'com.squareup.leakcanary:leakcanary-android:1.4-beta2'
    productionCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.4-beta2'
}

**Comment by mja46** [comment]
![mixpanel](https://cloud.githubusercontent.com/assets/3807328/20173958/3332af10-a76e-11e6-9b5d-a9bcadeea2c6.PNG)

how to change MIXPANEL_TOKEN value? because of that Error:(15, 47) error: illegal start of expression on BuildConfig.java

**Comment by rakawestu** [comment]
Did you build the SDK manually? 
I suggest you follow installation [here](https://github.com/veritrans/veritrans-android/wiki/SDK-Installation).

If you want to build manually you need to read [this instructions](https://github.com/veritrans/veritrans-android/wiki/How-to-Build-SDK-from-Source).

**Comment by mja46** [comment]
ok thanks

**Comment by AdamFM** [comment]
how i can get $version ?

**Comment by rakawestu** [comment]
@AdamFM 
Please see [release section](https://github.com/veritrans/veritrans-android/releases) to see latest version and the release notes.

**Comment by AdamFM** [comment]
BASE_URL refer to? api ? i can't use sample

**Comment by rakawestu** [comment]
Yes this SDK required backend implementation.
Please refer to [this reference](https://github.com/veritrans/veritrans-android/wiki/Implementation-for-Merchant-Server).

**Comment by AdamFM** [comment]
nah backend implementation itu dari kita sendiri? atau midtrans udh punya? trus cara make sample nya gimana ini mas?

**Comment by rakawestu** [comment]
@AdamFM
Yes. Merchant sendiri yg harus implement karena di situ butuh otentikasi `Server Key` yg hanya boleh disimpen di backend (gak boleh di mobile)

**Comment by AdamFM** [comment]
referensi untuk Implementation for Merchant Server, masih kurang mengerti saya.. untuk mudah nya seperti apa ya?

**Comment by rakawestu** [comment]
@AdamFM ada contohnya bisa liat di repo saya
https://github.com/rakawestu/veritrans-mobile-snap
