### ISSUE TITLE
error inflating layout

### ISSUE THREAD

**Issue by porpuera** [veritrans/veritrans-android#168]
when i click this button error.
 uiBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Logger.i("config>clientkey:" + MidtransSDK.getInstance().getClientKey());
                Logger.i("config>merchantUrl:" + MidtransSDK.getInstance().getMerchantServerUrl());
                Logger.i("config>sdkurl:" + MidtransSDK.getInstance().getSdkBaseUrl());
                Logger.i("config>timeout:" + MidtransSDK.getInstance().getRequestTimeOut());
                MidtransSDK.getInstance().setTransactionRequest(initializePurchaseRequest(UI_FLOW));
                MidtransSDK.getInstance().startPaymentUiFlow(MainActivity.this);
            }
        });

this error log : 
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.veritranssample/com.midtrans.sdk.uikit.activities.UserDetailsActivity}: android.view.InflateException: Binary XML file line #32: Error inflating class <unknown>

how to solve this.?

thanks before.

**Comment by rakawestu** [comment]
Hi @porpuera.

 Could you elaborate the way you initialize the SDK? Also more logs if possible.

**Comment by porpuera** [comment]
i got the code from this file https://github.com/veritrans/veritrans-android/blob/master/sdk-example/src/main/java/com/midtrans/sdk/sample/MainActivity.java and initialize the SDK same like on MainActivity.java.

**Comment by rakawestu** [comment]
@porpuera Did you also use this code?
```Java
           // SDK initiation for UIflow
            SdkUIFlowBuilder.init(this, BuildConfig.CLIENT_KEY, BuildConfig.BASE_URL, this)
                    .setDefaultText("open_sans_regular.ttf")
                    .setSemiBoldText("open_sans_semibold.ttf")
                    .setBoldText("open_sans_bold.ttf")
                    .buildSDK();
```

You need to set font with same name as supplied on builder at `assets` directory.

**Comment by porpuera** [comment]
ok thanks, i miss the asset fonts.

but i have any problem.

this 
CLIENT_KEY = "VT-client-obH*************";
BASE_URL = "https://api.sandbox.veritrans.co.id/v2";

when i get retrieving payment methods i got error dialog "failed to registering transaction method"

how to solve this?

**Comment by rakawestu** [comment]
Hi @porpuera.

- Client key configuration is correct.
- Base URL is incorrect because you need to implement your own merchant server. Please take a look at reference of merchant server implementation [here](https://github.com/veritrans/veritrans-android/wiki/Implementation-for-Merchant-Server).

**Comment by finn-deagle** [comment]
permisi mas @rakawestu , saya punya masalah seperti diatas. ketika saya klik button UIFLOW dan button pembayaran yang lain muncul error seperti yang diatas. kira - kira masalahnya apa ya?

KONFIGURASI GRADLE saya sperti dibawah :
CLIENT_KEY = "VT-client-5de17Vho*******"
BASE_URL = "https://app.sandbox.midtrans.com/snap/v1/transactions"

**Comment by rakawestu** [comment]
@finn-deagle Did you implement the merchant server?
Please take a look at this page.

[https://github.com/veritrans/veritrans-android/wiki/Implementation-for-Merchant-Server](https://github.com/veritrans/veritrans-android/wiki/Implementation-for-Merchant-Server)

**Comment by finn-deagle** [comment]
oh yes, I See.

I have more question, to create "token" I must send request to
https://app.sandbox.midtrans.com/snap/v1/transactions, with authorization
header.???

**Comment by dindatisi** [comment]
hi @finn-deagle for faster response, please send your questions to support@midtrans.com as we don't always monitor the issues here. thanks
