### ISSUE TITLE
need merchant url tester

### ISSUE THREAD

**Issue by dss-gplay** [veritrans/veritrans-android#218]
Hi, do you have any MERCHANT_BASE_URL_SANDBOX url and MERCHANT_CLIENT_KEY_SANDBOX  key to be tested? currently we are developing both mobile and server side so we can't test the sample code here.

thanks

**Comment by rakawestu** [comment]
Hi @dss-gplay, you can test using one of our example code of merchant server here.

https://github.com/rakawestu/veritrans-mobile-snap

You can deploy it anywhere.
The easiest one is on heroku and then pass the URL and client key on the SDK example project.
