### ISSUE TITLE
SDK Didn't Send payment_type JSON Into Request Data

### ISSUE THREAD

**Issue by mania25** [veritrans/veritrans-android#224]
I have a problem with integrating veritrans android sdk on my project, every time i try to do checkout/payment, i've always got error invalid payment_type, and when i see the logs, i didn't see the sdk include payment_type data into JSON request, and everytime i tried to do payment using another payment method (ex. bank transfer, BCA Clickpay) , it always send same request JSON data

![image](https://cloud.githubusercontent.com/assets/7329402/22029333/cc09738a-dd0c-11e6-8080-9a151b46edba.png)

i don't know if it's bug from sdk or what?I'm using merchant backend nodejs server from this github: https://github.com/veritrans/mobile-merchant-server

**Comment by rakawestu** [comment]
@mania25 Which SDK version did you use? 
If you use version 1.x.x (not 0.11.x) the merchant example is [here](https://github.com/rakawestu/veritrans-mobile-snap)

**Comment by mania25** [comment]
@rakawestu thank you for replay, did you have nodejs version for that? because i must configured GO Lang first, and i didn't have any experience with GO lang, i'm using android SDK version 1.2.8

**Comment by rakawestu** [comment]
@mania25 Currently we don't have any example using NodeJS.
But we have a guide for merchant server implementation, you can follow at [this wiki](https://github.com/veritrans/veritrans-android/wiki/Implementation-for-Merchant-Server).

**Comment by mania25** [comment]
@rakawestu okay, i've already tried to deploy merchant backend server into heroku cloud, and it works now, thank you
