### ISSUE TITLE
base_url core kit

### ISSUE THREAD

**Issue by porpuera** [veritrans/veritrans-android#246]
Halo mas itu merchant base_url maksudnya url buat apa ya?
saya agak bingung base_url nya karena token untuk transaksi sudah di generate dari server kami sendiri.

**Comment by rakawestu** [comment]
Checkout Token di generate juga oleh SDK ini.

Jadi merchant cukup menyediakan url merchant server ke SDK untuk melakukan checkout.

Misalnya URL untuk checkout adalah `https://merchant.com/charge` (`/charge` ini wajib untuk saat ini).
Jadi merchant cukup provide `https://merchant.com/` di SDK.

**Comment by porpuera** [comment]
makasih mas sebelumnya udah di bales.
itu response dari /charge apa aja ya isinya?
maaf mas sebelumnya banyak nanya soalnya baru sekali pake midtrans :)

**Comment by rakawestu** [comment]
@porpuera 
Ini mas boleh dilihat di wiki kita.

https://github.com/veritrans/veritrans-android/wiki/Implementation-for-Merchant-Server

Intinya merchant server ini buat redirect request checkout dari mobile SDK ke backend Midtrans. nanti response apapun dari backend Midtrans akan langsung jadi response nya.

**Comment by brotherbarz** [comment]
@rakawestu midtrans nyediain sandbox buat merchant base_urlnya gak mas? atau contoh script php buat penengah antara android sdk dan server midtrans?
terimakasih

**Comment by porpuera** [comment]
@rakawestu mas cara dapetin card_token pas abis konfirmasi 3d secure webview gimana ya? saya ikutin yg ini https://github.com/veritrans/veritrans-android/blob/3ac61149eecebb32a0bd555d5f2c55adf8ce8ddc/documentation/credit-card.md#handle-3d-secure-authorization dapet url callback nya doang.

**Comment by rakawestu** [comment]
@brotherbarz saat ini belum, tapi kita menyediakan sample di PHP dan Go
[https://github.com/rizdaprasetya/midtrans-mobile-merchant-server--php-sample-](https://github.com/rakawestu/veritrans-mobile-snap)
[https://github.com/rakawestu/veritrans-mobile-snap](https://github.com/rakawestu/veritrans-mobile-snap)

**Comment by rakawestu** [comment]
@porpuera token didapatkan di step sebelumnya saat melakukan get card token
```java
// CardTokenRequest class contains card details required for getting token.
CardTokenRequest cardTokenRequest = new CardTokenRequest(cardNumber, cvv, month, year, midtransSDK.getClientKey());
// Optional mode
cardTokenRequest.setIsSaved(true); // Set to true if this token will be used later (one click or two click)
cardTokenRequest.setTwoClick(true); // Set to true if using two click
cardTokenRequest.setSavedTokenId(SAVED_TOKEN_ID); // Set the saved token id if using two click
// Start the tokenize
midtransSDK.getCardToken(cardTokenRequest, new CardTokenCallback() {
    @Override
    public void onSuccess(TokenDetailsResponse response) {
       // Get token
       String tokenId = response.getTokenId();
       // Redirect URL
       String redirectUrl = response.getRedirectUrl();
    }

    @Override
    public void onFailure(TokenDetailsResponse response, String reason) {
        //actionGetCardTokenFailure(response, reason);
    }

    @Override
    public void onError(Throwable error) {
        //actionGetCardTokenError(error);
    }
});
```

Jadi `tokenId` tersebut baru **valid** setelah melalui 3DS lewat redirect URL tersebut.

**Comment by brotherbarz** [comment]
@rakawestu terimakasih mas atas tanggapannya. sudah saya implementasikan dan dapat callback dengan format `{"token_id":"8d7d450d-bfa3-4478-a3df-633a74beb63f"}`. tapi kenapa selalu muncul error **Failed to registering transaction** ya di aplikasi mobile saya?
Fyi saya menggunakan sdk-example

**Comment by rakawestu** [comment]
Kalo boleh tahu Snap URL yang di hit oleh merchant server apa ya? 
Coba update ke sini.
```
sandbox: https://app.sandbox.midtrans.com/snap/v1/transactions
prod: https://app.midtrans.com/snap/v1/transactions
```
Kalo gak salah masih nembak snap URL yg lama ini.
```
sandbox: https://app.sandbox.midtrans.com/snap/v1/pay
prod: https://app.midtrans.com/snap/v1/pay
```

**Comment by brotherbarz** [comment]
@rakawestu saya Snap URL nya pakai `https://app.sandbox.midtrans.com/snap/v1` mas
kalau pakai yang mas jabarin di atas malah kosong callbackannya.

**Comment by rakawestu** [comment]
@brotherbarz mungkin mas nembak snap nya ketambahan URL `/charge` jadi `https://app.sandbox.midtrans.com/snap/v1/transactions/charge`.

Harusnya itu static bukan ketambahan URL lain.

**Comment by krisnamargono** [comment]
@rakawestu mas, saya juga ngalamin error ini Failed to registering transaction. Padahal snap url nya udah pakai yang ini 
sandbox: https://app.sandbox.midtrans.com/snap/v1/transactions
prod: https://app.midtrans.com/snap/v1/transactions
apa yg kurang lagi ya? saya ikutin guide dari link yang ini https://mobile-docs.midtrans.com/#getting-started

**Comment by brotherbarz** [comment]
@krisnamargono kamu script php buat servernya pake yang mana? aku udah solved ni. mungkin bisa bantu jawab

**Comment by krisnamargono** [comment]
@brotherbarz masalahnya keknya ada di android nya sih ini. Soalnya yg iOS punya udah bisa. Kalo tokennya sudah didapat dari API di server, berarti kita tinggal panggil fungsi ini aja kan?
`MidtransSDK.getInstance().startPaymentUiFlow(ACTIVITY_CONTEXT);`
Soalnya dari guide yg ada di link di atas, ga ada fungsi yang minta tokennya gitu

**Comment by brotherbarz** [comment]
@krisnamargono `TransactionRequest` di isi apa aja mas?

**Comment by krisnamargono** [comment]
@brotherbarz untuk sekarang sih masih di hardcode. Ga boleh di hardcode ya harus sama kek yg di server nya?

**Comment by brotherbarz** [comment]
@krisnamargono bisa aja kok. gabisa di lampirin contoh kodingan initial sampe manggil UiFlownya?
aku si manggilnya kaya gini ngikutin example yang ada
```
UIKitCustomSetting uisetting = new UIKitCustomSetting();
uisetting.setShowPaymentStatus(true);
SdkUIFlowBuilder.init(this, client_key, base_url, this)
                    .setExternalScanner(new ScanCard()) 
                    .enableLog(true)
                    .useBuiltInTokenStorage(true)
                    .setDefaultText("open_sans_regular.ttf")
                    .setSemiBoldText("open_sans_semibold.ttf")
                    .setBoldText("open_sans_bold.ttf")
                    .setUIkitCustomSetting(uisetting) 
                    .buildSDK();
TransactionRequest transactionRequestNew = new TransactionRequest(System.currentTimeMillis()+"", 800000);
MidtransSDK.getInstance().setTransactionRequest(transactionRequestNew);
MidtransSDK.getInstance().startPaymentUiFlow(MyActivity.this);
```

**Comment by krisnamargono** [comment]
@brotherbarz sorry baru reply lagi. udah bisa nih skg ternyata salah di baseUrl nya. thank youu

**Comment by AdamFM** [comment]
Misi mas mau nanya untuk method pembayaran langsung ke bank transfer, kan pakai method ini : MidtransSDK.getInstance().startBankTransferUIFlow(ACTIVITY_CONTEXT);
ini kok error ya?

**Comment by kholilibnu** [comment]
misi mas mau tanya, pas checkout transaksi kok saya gagal terus ya?

**Comment by dindatisi** [comment]
@kholilibnu error message nya apa ya? anda pakai core flow atau ui flow?

**Comment by alamse** [comment]
@rakawestu untuk return json dari end point  `/charge` yang benar `token` atau `token_id` ?

**Comment by alamse** [comment]
ada infokah untuk hal ini ? saya buat satu issue terkait ini. https://github.com/veritrans/mobile-merchant-server/issues/3 mohon maaf jika salah tempat.

**Comment by rakawestu** [comment]
@alamse 

The json response should be

```json
{
    "token" : "your token"
}
```

The `token_id` field is used on our old SDK. It's not used in the latest version.

**Comment by rakawestu** [comment]
@AdamFM Can you elaborate more about the error?
