### ISSUE TITLE
Failed to Registering Transaction

### ISSUE THREAD

**Issue by huteri** [veritrans/veritrans-android#266]
Hey guys, I get this error and there is not other log, how am I supposed to fix this? Seriously, I already enable debug log to true, but still no helping message on how I can fix this. You guys seriously need to have better error handling to help devs fix the issue easier. 

This is how I init the sdk

```
SdkUIFlowBuilder
                .init(this, BuildConfig.VERITRANS_CLIENT_KEY, BuildConfig.VERITRANS_BASE_URL, transactionResult -> {
                    Log.d("TAG", transactionResult.getStatus());
                })
                .enableLog(true)
                .buildSDK();

CreditCard creditCard = new CreditCard();
        creditCard.setSaveCard(true);

        TransactionRequest transactionRequest = new TransactionRequest("12312312312", 1000000);
        transactionRequest.setCreditCard(creditCard);
        transactionRequest.setCardPaymentInfo("normal", true);

        MidtransSDK.getInstance().setTransactionRequest(transactionRequest);
        MidtransSDK.getInstance().startCreditCardUIFlow(this);
```

**Comment by huteri** [comment]
and, do we need to add something to proguard to make it work? please add proguard rules

**Comment by krisnamargono** [comment]
Same problem. Have you found any solution for this problem?

**Comment by krisnamargono** [comment]
see here, maybe it has the same issue as you https://github.com/veritrans/veritrans-android/issues/246

**Comment by huteri** [comment]
yes, thank you, it's solved, the devs here should think the users as devs, not as customers #268

**Comment by krisnamargono** [comment]
Org Indonesia kan? Mau tanya dong, cara betulinnya gimana ya? Soalnya Snap URL nya udah bener harusnya nih

**Comment by huteri** [comment]
@krisnamargono iya orang indo kok, hehe, bisa banyak si faktorny, pastiin ini bener
```
stagingCompile 'com.midtrans:uikit:1.3.3-SANDBOX'
productionCompile 'com.midtrans:uikit:1.3.3'
``

jad yang sandbox pake version yang ada sandbox di belakangnya, kalau masih salah, coba implemenet pull request dari saya, trus lihat log apa errorny

**Comment by krisnamargono** [comment]
hmm kalo km masalahnya karena yg di gradle itu aja berarti? yg code buat init sampe .startCreditCardUIFlow ga ada yg berubah?

**Comment by huteri** [comment]
Iya kalo kasus saya masalahnya karena url base salah, jadi waktu veritrans
sdk POST /charge balikan dri serverny 404 not found, dan di convert jadi
message Failed to registering transaction ke ui ny..

-- 
Huteri Manza

On March 9, 2017 at 16:38:53, krisnamargono (notifications@github.com)
wrote:

hmm kalo km masalahnya karena yg di gradle itu aja berarti? yg code buat
init sampe .startCreditCardUIFlow ga ada yg berubah?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/veritrans/veritrans-android/issues/266#issuecomment-285302481>,
or mute the thread

**Comment by krisnamargono** [comment]
Kalo boleh tau, line yang ini 
`TransactionRequest transactionRequest = new TransactionRequest("12312312312", 1000000);`
di hard code juga ga akan masalah?

**Comment by huteri** [comment]
itu order id sama price bakal di krim ke server kita dengan api /charge
itu, jadi selama server kita bisa balikin 200 dan sesuai yang diinginkan
oleh veritrans ya gak masalah di hardcode. Kalo balikinny selain 200, bakal
muncul message itu..

-- 
Huteri Manza

On March 9, 2017 at 17:06:18, krisnamargono (notifications@github.com)
wrote:

di hard code juga ga akan masalah?

**Comment by krisnamargono** [comment]
@huteri sorry baru reply lagi. Ternyata bener nih baseUrl nya yg salah.. Thank you yah
