### ISSUE TITLE
Failed to registering transaction

### ISSUE THREAD

**Issue by zihadrizkyef** [veritrans/veritrans-android#313]
Mas, di server udah di implementasikan midtransnya dan berhasil dapet token lewat curl. Tapi saat di jalanin di mobile munculnya **Failed to registering transaction**, di logcat tulisannya Retrofit 404 not found.

Ini code mobilenya

    SdkUIFlowBuilder.init(
            this,
            "VT-client-XXXXXXXXXXXX",
            "http://XXXXXXXXXX.com",
            new TransactionFinishedCallback() {
                @Override
                public void onTransactionFinished(TransactionResult transactionResult) {
                    Toast.makeText(MainActivity.this, "transaction finished", Toast.LENGTH_SHORT).show();
                }
            }).buildSDK();

    Button btn_pay_now = (Button) findViewById(R.id.btn_pay_now);
    btn_pay_now.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            TransactionRequest transactionRequest = new TransactionRequest(String.valueOf(System.currentTimeMillis()), Double.parseDouble("80000"));

            ItemDetails item1 = new ItemDetails("19", 20000, 1, "mukena merah");
            ItemDetails item2 = new ItemDetails("13", 30000, 2, "baso galak");
            ArrayList<ItemDetails> itemDetailsArray = new ArrayList<>();
            itemDetailsArray.add(item1);
            itemDetailsArray.add(item2);
            transactionRequest.setItemDetails(itemDetailsArray);

            BillInfoModel billInfo = new BillInfoModel("bill key", "bill value");
            transactionRequest.setBillInfoModel(billInfo);

            MidtransSDK.getInstance().setTransactionRequest(transactionRequest);

            CreditCard creditCardOption = new CreditCard();
            creditCardOption.setSaveCard(false);
            creditCardOption.setSecure(false);
            creditCardOption.setBank(BankType.BCA);
            creditCardOption.setChannel(CreditCard.MIGS);
            transactionRequest.setCreditCard(creditCardOption);
            transactionRequest.setCardPaymentInfo(getResources().getString(R.string.card_click_type_none), false);

            MidtransSDK.getInstance().startPaymentUiFlow(MainActivity.this, PaymentMethod.BANK_TRANSFER);
        }
    });

kira2 knp yah muncul error itu? mohon bantuannya

**Comment by rakawestu** [comment]
Udah di implement merchant server-nya yg `http://XXXXXXXXXX.com` ?

**Comment by zihadrizkyef** [comment]
sudah mas

**Comment by rakawestu** [comment]
@zihadrizkyef 

Kelihatannya ada yg kurang implementasi di SDK nya:

Belum ada penggunaan `setTransactionRequest`.

```java
MidtransSDK.getInstance().setTransactionRequest(transactionRequest);
```

Kemudian bisa dipastikan lagi implementasi merchant servernya.

Misalkan server URL yg di provide ke SDK itu `https://server.com/` maka di server tersebut sudah ada endpoint

```
POST https://server.com/charge
```

Selanjutnya, udah dicoba belum bila endpoint tersebut dihit manual lewat REST client (misal Postman).

Pastikan response nya seperti ini

```json
{
    "token" : "xxxx"
}
```

**Comment by zihadrizkyef** [comment]
MidtransSDK.getInstance().setTransactionRequest(transactionRequest);
Sudah ko mas di tengah2 code, di atas seting credit card
Dan untuk test merchant server dengan curl sudah bisa dapet token. Tapi di mobile tetep muncul error Failed to registering transaction

**Comment by HizkiaSetiadi** [comment]
Saya juga mengalami Error yang sama... Apakah sudah ada solusinya untuk masalah error 404 ini?

**Comment by dindatisi** [comment]
hi all, untuk issue ini umumnya karena ada kesalahan implementasi di merchant server. Apa boleh kami minta url nya untuk diinvestigasi?

**Comment by HizkiaSetiadi** [comment]
ini url merchantnya http://ajpand.azurewebsites.net/api/policy/charge

**Comment by zihadrizkyef** [comment]
saya ganti BaseURL jadi http://xxxxxxx.com/charge/index.php and it works.. i don't know, but it's working

**Comment by rakawestu** [comment]
@HizkiaSetiadi It should return the token.

Instead here is the response for your URL

```json
{
  "$id": "1",
  "Message": "No HTTP resource was found that matches the request URI 'http://ajpand.azurewebsites.net/api/policy/charge'."
}
```

**Comment by dindatisi** [comment]
hi @HizkiaSetiadi untuk error ini sudah di-reply juga via email oleh tim support kami dengan no. tiket 22527. Thanks
