### ISSUE TITLE
[Solved] Get NullPointerException in MidtransSDK.getInstance()

### ISSUE THREAD

**Issue by cphs** [veritrans/veritrans-android#343]
I got `NullPointerException` when call `MidtransSDK.getInstance().setTransactionRequest(transactionRequest);`

How to init the instance? is it only 

SdkUIFlowBuilder.init(CheckoutPaymentActivity.this, Constants.MIDTRANS_CLIENT_KEY,
        Constants.MIDTRANS_BASE_URL, new TransactionFinishedCallback() {
          @Override
          public void onTransactionFinished(TransactionResult result) {
              // Handle finished transaction here.
          }
        });

**Comment by rakawestu** [comment]
You need to add `buildSDK()` in the end of init statement.

```java
SdkUIFlowBuilder.init(this, Constants.MIDTRANS_CLIENT_KEY,
Constants.MIDTRANS_BASE_URL, new TransactionFinishedCallback() {
    @Override
   public void onTransactionFinished(TransactionResult result) {
       // Handle finished transaction here.
   }
}).buildSDK();
```
