### ISSUE TITLE
Got error when trying to open the SDK

### ISSUE THREAD

**Issue by cphs** [veritrans/veritrans-android#345]
[EDITED]
This is the real error.

Unable to start activity ComponentInfo{com.cphs.midtrans/com.midtrans.sdk.uikit.activities.UserDetailsActivity}: android.view.InflateException: Binary XML file line #32: Error inflating class

the previous one is my fault :), I got this error in example also

**Comment by rakawestu** [comment]
Hi @cphs which version of SDK did you use?

**Comment by cphs** [comment]
compile 'com.midtrans:uikit:1.6.1-SANDBOX'

**Comment by cphs** [comment]
I try the example also and get 

Unable to start activity ComponentInfo{com.cphs.midtrans/com.midtrans.sdk.uikit.activities.UserDetailsActivity}: android.view.InflateException: Binary XML file line #32: Error inflating class <unknown>

can you help me?

**Comment by cphs** [comment]
Remove `.setDefaultText("open_sans_regular.ttf")` when build the SDK, then fixed
