### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by cphs** [veritrans/veritrans-android#347]
where I cang get `Constants.ADDRESS_TYPE_BILLING` ?

and what is the differences `ShippingAddress` for transaction request and `UserAddress` and save as shipping address?
Should I use both of them ?

And I get 405 after fill the user detail, do you know why?

**Comment by rakawestu** [comment]
@cphs In which step did you get `405` error code?

Based on [status code documentation](https://mobile-docs.midtrans.com/#code-4xx), `405` is `HTTP method is not allowed`,

**Comment by cphs** [comment]
fixed, already discuss in skype group
