### ISSUE TITLE
Custom Field Tidak Konsisten

### ISSUE THREAD

**Issue by alamse** [veritrans/veritrans-android#355]
Hi @rakawestu ,

saya mencoba untuk mengirimkan custom_field1 pada saat request token ke server, json yang sy terima di server adalah sbb : 

```
{
...
"custom_field1":"...."
...
}
```

sedangkan untuk di iOS, jika saya set custom field dalam bentuk list of dictionary, misalkan 

```
let customField = [
["user_id" : "...."]
]
```

maka json yang saya terima:

```
{
...
"user_id" : "..."
...
}
```
pertanyaan saya adalah, apakah memungkinkan untuk mengirimkan custom field dalam bentuk key value seperti di iOS ?

**Comment by rakawestu** [comment]
@alamse Nope, di versi terbaru iOS juga harusnya sudah sama dengan Android hanya support `custom_field1`, `custom_field2` dan `custom_field3`.

Apabila yg mau di pass itu JSON, maka sebaiknya di di pass saja json dalam bentuk string nya.

**Comment by alamse** [comment]
@rakawestu ok.
