### ISSUE TITLE
I am using Midtrans in mobile website , i want to pay in our native mobile apps using Webview Failed

### ISSUE THREAD

**Issue by billyriantono** [veritrans/veritrans-android#361]
Hi all,
My Team have integrate Midtrans for payment solution in mobile website, we try using our payment page in mobile site in our native apps using webview but always failed to show midtrans popup ? there is any workaround for this situation ?

Thanks.

**Comment by rakawestu** [comment]
@billyriantono Did you use `veritrans-android` library ?

If you're using WebView I'm afraid there is some problem with loading the Midtrans javascript in WebView. 

We recommends you to use `veritrans-android` since it's native and it uses same backend as Midtrans web solution.

**Comment by billyriantono** [comment]
Hi thanks raka the problem is solved :D
