### ISSUE TITLE
Mandiri bill payment method?

### ISSUE THREAD

**Issue by 672009095** [veritrans/veritrans-android#366]
where is mandiri bill payment method for use echannel payment type for sdk version
'com.midtrans:uikit:1.7.1' ? or i must use corekit for enable that?

i use this code for choose payment method:
MidtransSDK.getInstance().startPaymentUiFlow(Actiuvity, PaymentMethod.XXX);

or need another code for enable mandiri bill payment

thanks, best regards.

**Comment by rakawestu** [comment]
By default you can enable any payment methods by using Midtrans dashboard [https://account.midtrans.com](https://account.midtrans.com).

It's on `Settings -> Snap Preferences` menu.

**Comment by 672009095** [comment]
this isue closed, by use mandiri bill payment method for use echannel payment type
just suggest, use same name method or same params for sdk android and ios sdk for reduce miss understanding
