### ISSUE TITLE
Failed to retrieve transaction details

### ISSUE THREAD

**Issue by mahasadhu** [veritrans/veritrans-android#373]
Hi there, 

I got an error dialog saying Failed to retrieve transaction details, along with 404 retrofit error on the log cat. I have implemented the merchant server, and the /charge already returns a token. 
![image](https://cloud.githubusercontent.com/assets/13914485/26581049/605e64c8-456d-11e7-897a-e8871d39aeee.png)

Following is the android code

        SdkUIFlowBuilder.init(
                this,
                "VT-client-blablabla",
                "http://blabla.com/",
                new TransactionFinishedCallback() {
            @Override
            public void onTransactionFinished(TransactionResult transactionResult) {
                Log.e("TRANSACTION RESULT", new Gson().toJson(transactionResult));
            }
        })
        .buildSDK();

        TransactionRequest transactionRequest = new TransactionRequest("asdasdqwe01", 100000);

        ItemDetails itemDetails1 = new ItemDetails("1", 100000, 1, "Base Service");

        ArrayList<ItemDetails> itemDetailses = new ArrayList<>();
        itemDetailses.add(itemDetails1);

        CreditCard creditCardOptions = new CreditCard();
        creditCardOptions.setSaveCard(false);
        creditCardOptions.setSecure(false);
        transactionRequest.setCreditCard(creditCardOptions);

        transactionRequest.setCardPaymentInfo(getString(R.string.card_click_type_none), false);

        MidtransSDK.getInstance().setTransactionRequest(transactionRequest);

        MidtransSDK.getInstance().startPaymentUiFlow(TestPaymentActivity.this);

We also have sent you a support ticket (23990)
Looking forward to your response. Thank you.

**Comment by vanbungkring** [comment]
hi @mahasadhu  have you implement merchant server?

**Comment by derohimat** [comment]
yes I get same error

**Comment by mahasadhu** [comment]
@vanbungkring Yes i have. I already mention that above, take a closer look at my question.

I have implement it and the /charge endpoint already returns the token if i test it using postman.
Still, it stuck at "Failed to retrieve transaction details".

I have try to change the url for the snap backend in my merchant server, from app subdomain, api subdomain, /transaction endpoint, /pay endpoint etc, still no luck.

**Comment by derohimat** [comment]
@mahasadhu are you using sandbox merchant url ?

**Comment by mahasadhu** [comment]
Issue fixed by updating the SDK version from 1.7.1-SANDBOX to 1.7.3-SANDBOX

Sorry I didn't realize that there was a new version released yesterday

**Comment by mahasadhu** [comment]
@derohimat Yep, I am using sandbox in both SDK and snap URL

**Comment by derohimat** [comment]
I got issue because 

```
    sandboxCompile "com.midtrans:uikit:$VERITRANS_VERSION-SANDBOX"
    productionCompile "com.midtrans:uikit:$VERITRANS_VERSION"

    compile "com.midtrans:uikit:$VERITRANS_VERSION"
```

and fixed after change to 


```
    sandboxCompile "com.midtrans:uikit:$VERITRANS_VERSION-SANDBOX"
    productionCompile "com.midtrans:uikit:$VERITRANS_VERSION"
```

**Comment by mahasadhu** [comment]
@derohimat Ah, i see, seems like previously your app is using the production SDK instead of the sandbox SDK, while your merchant server is using sandbox snap URL.
