### ISSUE TITLE
android:allowBackup should not be set by a library

### ISSUE THREAD

**Issue by Jeff-Kidzie** [veritrans/veritrans-android#70]
The android:allowBackup=true option in the manifest causes errors while merging with our manifest. Because we already set it to false.

>Error:Execution failed for task :app:processDevDebugManifest
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:47:9-36
  	is also present at [id.co.veritrans:coreflow:0.10.11-SANDBOX] AndroidManifest.xml:12:9-35 value=(true).
  	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:45:5-221:19 to override.`

This  tag should not in library, because the default is true. And this setting should use by the app, not by library

**Comment by rakawestu** [comment]
Thanks for the bugs report @Jeff-Kidzie.
We will remove this tag to prevent this error 👍
