### ISSUE TITLE
Could not find property 'MIXPANEL_TOKEN_SANDBOX'

### ISSUE THREAD

**Issue by ntaloventi** [veritrans/veritrans-android#89]
https://api.sandbox.veritrans.co.id/v2/

return 404
any info?

**Comment by rakawestu** [comment]
@ntaloventi There are no endpoint there so it will return `404`.
If you want to get card token try this link
`https://api.sandbox.veritrans.co.id/v2/token`

And the params you can look here.
[http://docs.veritrans.co.id/en/api/methods.html#Get_Token](http://docs.veritrans.co.id/en/api/methods.html#Get_Token)
